<a href="https://colab.research.google.com/github/drm1072/Data_Sets/blob/main/Data_Science_Basics_with_Python_part_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np  #Numpy provides fast mathematical function processing
# We use np as a quick way to execute code; samething with pandas as pd

In [3]:
# Single dimensional array
data = np.array([7,25,97])

In [4]:
# This is one row which rperesents one dimension
data

array([ 7, 25, 97])

In [15]:
#Single dimensional array
data = np.array([7,17,6, 89])

In [17]:
data

array([ 7, 17,  6, 89])

You should notice that the entire dataframe has been converted to floats.

In [18]:
#Now lets create a new array
data=np.array([4,0])

data2=np.array([0,2])

In [19]:
#addition with our arrays
data3 = data+data2

In [20]:
data3

array([4, 2])

In [21]:
#lets multiple a given number (I choose the number 4)
data4=6*data3

In [23]:
# 4 times 2 = 8
data4

array([24, 12])

In [25]:
#lets create a new numpy array
data5=np.array([4,2])

In [26]:
# Lets multiplye dataframe array 4 times 5
data6=data4*data5

In [27]:
#12 times 4 is 48
#2 times 12 is 24
data6

array([96, 24])

In [28]:
#Multidimensional array
#lets create a multidimensional array which adds height
#this is now 3 dimensional because we have length vs width vs height
data7 = np.array([[2, 13, 89], [34, 16, 841], [1, 2, 4]])

In [33]:
data8=np.array([[2, 1, 6], [1, 2, 3], [1, 9, 0]])

In [34]:
#The code doesnt work because python doesnt allow us because array is not equivalent
data9=data7+data8

In [35]:
data9

array([[  4,  14,  95],
       [ 35,  18, 844],
       [  2,  11,   4]])

In [36]:
# creating number 10
data10=np.array([[3, 1, 7], [4, 5, 8], [1, 2, 7]])

In [37]:
#multipying arrays
data11=data9*data10

In [38]:
data11

array([[  12,   14,  665],
       [ 140,   90, 6752],
       [   2,   22,   28]])

In [39]:
#lets locate some values
data11[1]

array([ 140,   90, 6752])

In [40]:
data11[1][2]

6752

In [42]:
#It stops us here because the third place doesnt exist
#remember Python starts with 0 not 1
#the first number is 0 row or the 1st row, number 3 is the third feature or column
data11[0][2]

665

This means the 0 row
Number 2 column


In [43]:
#Lets transpose data or switch data around
data12=data11.T

In [44]:
data12

array([[  12,  140,    2],
       [  14,   90,   22],
       [ 665, 6752,   28]])

In [48]:
#This code arranges values in array from 0 to designated number
#I choose 64
data13=np.arange(64)

In [49]:
data13

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [52]:
#The resphape function moves our data frame array to 8 rows and 8 columns
data14=data13.reshape(8,8)

In [53]:
data14

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [55]:
#lets create a 3d array
#the reshape must equal amount of values in array
#8**=64
#4*4*4=64
data14=data13.reshape(4, 4, 4)

In [56]:
data14

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

ndim-the number of axes

shape-the dimensions of the arrray

size-the number of elements in the arrray

dtype-the data type of the elements of the array

In [57]:
data14.ndim

3

In [58]:
data14.shape

(4, 4, 4)

In [59]:
data14.size

64

In [60]:
#does math vertically
#It adds each dataframe together
np.sum(data14, axis = 0)

array([[ 96, 100, 104, 108],
       [112, 116, 120, 124],
       [128, 132, 136, 140],
       [144, 148, 152, 156]])

In [61]:
np.sum(data14, axis= 1)

array([[ 24,  28,  32,  36],
       [ 88,  92,  96, 100],
       [152, 156, 160, 164],
       [216, 220, 224, 228]])

In [62]:
data14

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [64]:
data15=np.array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [65]:
#Now lets combine the data vertically (axis 1)
np.concatenate([data14, data15], axis = 1)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47],
        [32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [66]:
#Now lets combine the data horizontally (axis 0)
data16=np.concatenate([data14, data15], axis = 0)

In [67]:
data16

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [68]:
#max value
np.max(data16)

63

In [69]:
#minimal value
np.min(data16)

0

In [70]:
#average of numbers
np.mean(data16)

31.5

In [71]:
#standard deviation
#the average numerical distance from the mean
np.std(data16)

18.472953201911167