<a href="https://colab.research.google.com/github/drm1072/Data_Sets/blob/main/Hyperparameter_Tuning_of_Machine_Learning_model_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**Tuning Hyperparameters of Machine Learning Model**

**In this Jupyter notebook, we will be tuning hyperparameters of a classification model built by random forest algorithm using scikit-learn package in Python.**

1. Make synthetic dataset

1.1. Generate the dataset
Tuning Hyperparameters of Machine Learning Model 

Dadrian Morgan



In [1]:
from sklearn.datasets import make_classification
#x var 200-rows 10-columns
X, Y = make_classification(n_samples=200, n_classes=2, n_features=10, n_redundant=0, random_state=1)

In [3]:
import pandas as pd


**1.2. Let's examine the data dimension**

**We can see that there are 100 rows (samples) and 5 columns (features) for the X variable and 100 rows and 1 column (class label) for the Y variable.**

In [2]:
X.shape, Y.shape 

((200, 10), (200,))

In [4]:
X

array([[-1.51107661,  0.60874908, -0.15323616, ..., -0.86482994,
        -0.20290111, -0.87142207],
       [ 1.44544531,  0.51896937,  0.64515265, ..., -1.04339961,
         0.04854689, -2.62101164],
       [ 0.37167029,  0.51350548, -1.39881282, ...,  0.14225137,
        -1.13283476,  1.85300949],
       ...,
       [-0.95090925, -0.21873346,  1.29354962, ..., -0.04586669,
        -0.97210712, -0.70435033],
       [-0.4466992 ,  0.74488454, -0.9612636 , ...,  0.61223252,
         1.67977906,  0.20437739],
       [ 1.00796648,  1.1253235 ,  0.43499832, ...,  0.44838065,
        -1.75951426,  0.39233491]])

In [8]:
pd.DataFrame(X)

0         1         2  ...         7         8         9
0   -1.511077  0.608749 -0.153236  ... -0.864830 -0.202901 -0.871422
1    1.445445  0.518969  0.645153  ... -1.043400  0.048547 -2.621012
2    0.371670  0.513505 -1.398813  ...  0.142251 -1.132835  1.853009
3    2.565453  0.145652  1.177052  ... -0.202694 -1.199798 -0.464115
4   -0.710656  1.050615  0.354602  ... -0.621252 -1.187774  1.131129
..        ...       ...       ...  ...       ...       ...       ...
195 -1.098083 -1.277636  0.419595  ...  0.032615  1.164204  0.758637
196  0.165211  1.937132 -1.307971  ... -0.696028 -0.162525  0.976296
197 -0.950909 -0.218733  1.293550  ... -0.045867 -0.972107 -0.704350
198 -0.446699  0.744885 -0.961264  ...  0.612233  1.679779  0.204377
199  1.007966  1.125323  0.434998  ...  0.448381 -1.759514  0.392335

[200 rows x 10 columns]

In [9]:
pd.DataFrame(Y)

0
0    1
1    0
2    0
3    1
4    1
..  ..
195  0
196  1
197  0
198  1
199  1

[200 rows x 1 columns]


**2. Data split (80/20 ratio)**

**2.1. Data split**

**A ratio of 80/20 is used for data splitting such that 80% goes to the training subset and 20% to the testing subset**

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)


**2.2. Let's examine the data dimension**

**Here we see that the training set has 160 rows and 10 columns while there are 160 rows and 1 column for the Y variable.**

In [11]:
X_train.shape, Y_train.shape

((160, 10), (160,))

**The testing set has 40 rows and 10 columns for the X variable while there are 40 rows and 1 column for the Y variable.**

In [12]:
X_test.shape, Y_test.shape

((40, 10), (40,))

**3. Building a simple machine learning model using Random Fores**t

**In the following blocks of codes, we will first start with building a random forest model. Finally, we will explore how to tune the hyperparameters (e.g. n_estimators and max_features) of the random forest algorithm.**

**We first start by importing the necessary libraries and assigning the random forest classifier to the rf variable.**

In [14]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rf = RandomForestClassifier(max_features=5, n_estimators=100)

**Now, we will be applying the random forest classifier to build a classification model using the rf.fit() function on the training data (e.g. X_train and Y_train).**

In [15]:
rf.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features=5,
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [16]:
rf.score(X_test, Y_test)

0.9


**The following 2 code cells also calculate the accuracy score of the RF model in predicting the test data (X_test) but performs it in 2 steps using rf.predict() and accuracy_score() functions.**

In [17]:
Y_pred = rf.predict(X_test)

In [18]:
accuracy_score(Y_pred, Y_test)

0.9

**The advantage of using this latter approach is that you have access to the predicted data values.**

In [19]:
Y_pred, Y_test

(array([0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
        1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1]),
 array([0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
        0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1]))

**4. Hyperparameter Tuning**

**Now we will be performing the tuning of hyperparameters of Random forest model. The hyperparameters that we will tune includes max_features and the n_estimators.**

**Note: Some codes modified from scikit-learn**

**Firstly, we will import the necessary modules.**

**The GridSearchCV() function from scikit-learn will be used to perform the hyperparameter tuning. Particularly, GridSearchCV() function can perform the typical functions of a classifier such as fit, score and predict as well as predict_proba, decision_function, transform and inverse_transform.**

**Secondly, we define variables that are necessary input to the GridSearchCV() function.**

In [20]:
from sklearn.model_selection import GridSearchCV
import numpy as np

max_features_range = np.arange(1,6,1)
n_estimators_range = np.arange(10,210,10)
param_grid = dict(max_features=max_features_range, n_estimators=n_estimators_range)
#input argument
rf = RandomForestClassifier()

grid = GridSearchCV(estimator=rf, param_grid=param_grid, cv=5)

In [24]:
import numpy as np
np.arange(1,100,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [21]:
grid.fit(X_train, Y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,
                                              oob_score=False,
                                              rando

In [ ]:
print("The best parameters are %s with a score of %0.2f"
      % (grid.best_params_, grid.best_score_))


**The best parameters are {'max_features': 1, 'n_estimators': 120} with a score of 0.90**

In [25]:
import pandas as pd

grid_results = pd.concat([pd.DataFrame(grid.cv_results_["params"]),pd.DataFrame(grid.cv_results_["mean_test_score"], columns=["Accuracy"])],axis=1)
grid_results.head()

max_features  n_estimators  Accuracy
0             1            10   0.73125
1             1            20   0.78750
2             1            30   0.81875
3             1            40   0.80000
4             1            50   0.83125


**6. Preparing data for making contour plots**

**Prior to making contour plots, we will have to reshape the data into a compatible format that will be recognized by the contour plot functions.**

**Firstly, we will be using Pandas' groupby() function to segment the data into groups based on the 2 hyperparameters: max_features and n_estimators.**

In [26]:
grid_contour = grid_results.groupby(['max_features','n_estimators']).mean()
grid_contour

Accuracy
max_features n_estimators          
1            10             0.73125
             20             0.78750
             30             0.81875
             40             0.80000
             50             0.83125
...                             ...
5            160            0.86875
             170            0.86250
             180            0.86250
             190            0.86250
             200            0.86875

[100 rows x 1 columns]


**Pivoting the data**

**Data is reshaped by pivoting the data into an m by n matrix where rows and columns correspond to the max_features and n_estimators, respectively.**

In [29]:
grid_reset = grid_contour.reset_index()
grid_reset.columns = ['max_features', 'n_estimators', 'Accuracy']
grid_pivot = grid_reset.pivot('max_features', 'n_estimators')
grid_pivot #moving data from rows to columns

Accuracy                    ...                           
n_estimators      10       20       30   ...      180      190      200
max_features                             ...                           
1             0.73125  0.78750  0.81875  ...  0.84375  0.85625  0.84375
2             0.82500  0.83125  0.85625  ...  0.86250  0.85000  0.86250
3             0.86875  0.84375  0.87500  ...  0.86875  0.86875  0.86875
4             0.87500  0.85625  0.86250  ...  0.86875  0.86250  0.86250
5             0.85000  0.86250  0.84375  ...  0.86250  0.86250  0.86875

[5 rows x 20 columns]

Finally, we assign the pivoted data into the respective x, y and z variables.

In [37]:
x = grid_pivot.columns.levels[1].values
y = grid_pivot.index.values
z = grid_pivot.values

In [38]:
x,y,z

(array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150, 160, 170, 180, 190, 200]),
 array([1, 2, 3, 4, 5]),
 array([[0.73125, 0.7875 , 0.81875, 0.8    , 0.83125, 0.84375, 0.825  ,
         0.825  , 0.85   , 0.85625, 0.8375 , 0.83125, 0.83125, 0.825  ,
         0.8375 , 0.8375 , 0.85   , 0.84375, 0.85625, 0.84375],
        [0.825  , 0.83125, 0.85625, 0.875  , 0.83125, 0.85   , 0.8625 ,
         0.84375, 0.8625 , 0.8625 , 0.85625, 0.85   , 0.8625 , 0.86875,
         0.8625 , 0.85625, 0.84375, 0.8625 , 0.85   , 0.8625 ],
        [0.86875, 0.84375, 0.875  , 0.8625 , 0.86875, 0.85625, 0.8375 ,
         0.85625, 0.86875, 0.875  , 0.875  , 0.85   , 0.85625, 0.8625 ,
         0.86875, 0.8625 , 0.875  , 0.86875, 0.86875, 0.86875],
        [0.875  , 0.85625, 0.8625 , 0.8625 , 0.875  , 0.85   , 0.8625 ,
         0.85   , 0.86875, 0.8625 , 0.875  , 0.86875, 0.86875, 0.8625 ,
         0.8625 , 0.86875, 0.8625 , 0.86875, 0.8625 , 0.8625 ],
        [0.85   , 0.8625 


**2D Contour Plot**

**Now, comes the fun part, we will be visualizing the landscape of the 2 hyperparameters that we are tuning and their influence on the accuracy score.**

In [31]:
! pip install plotly

In [39]:
import plotly.graph_objects as go

# X and Y axes labels
layout = go.Layout(
            xaxis=go.layout.XAxis(
              title=go.layout.xaxis.Title(
              text='n_estimators')
             ),
             yaxis=go.layout.YAxis(
              title=go.layout.yaxis.Title(
              text='max_features') 
            ) )

fig = go.Figure(data = [go.Contour(z=z, x=x, y=y)], layout=layout )

fig.update_layout(title='Hyperparameter tuning', autosize=False,
                  width=500, height=500,
                  margin=dict(l=65, r=50, b=65, t=90))

fig.show()


**3D Surface Plot**

**Let's add an extra dimension to the plot and we now have a 3D surface plot. The cool thing about this plot is that you can rotate the graph.**

In [40]:
import plotly.graph_objects as go


fig = go.Figure(data= [go.Surface(z=z, y=y, x=x)], layout=layout )
fig.update_layout(title='Hyperparameter tuning',
                  scene = dict(
                    xaxis_title='n_estimators',
                    yaxis_title='max_features',
                    zaxis_title='Accuracy'),
                  autosize=False,
                  width=800, height=800,
                  margin=dict(l=65, r=50, b=65, t=90))
fig.show()